---
- name: add hosts and host groups to pure storage arrays
  hosts: purefa1
  tasks:
    - name: get name of volume and datastore to use in multiple tasks
      set_fact:
        datastore_name: "{{ hostvars['vcenter']['datastore_name'] }}"

    - name: create new volume on purefa1
      delegate_to: localhost
      purestorage.flasharray.purefa_volume:
        name: "{{ datastore_name }}"
        size: "{{ hostvars['vcenter']['datastore_size'] }}"
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ api_token }}"
        state: "{{ vol_state | default('present') }}"

    - name: Mask Volume
      delegate_to: localhost
      purestorage.flasharray.purefa_hg:
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ api_token }}"
        hostgroup: "{{ hostvars['vcenter']['cluster_name'] }}"
        volume: "{{ datastore_name }}"
        state: "{{ vol_state | default('present') }}"

    - name: Get Volume Information from Purefa
      delegate_to: localhost
      purestorage.flasharray.purefa_info:
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ api_token }}"
        gather_subset: volumes
      register: pure_info

- name: manage datastores in vcenter
  hosts: vmware
  tasks:
    - name: rescan esxi hosts for new storage
      delegate_to: localhost
      community.vmware.vmware_host_scanhba:
        hostname: "{{ ansible_host }}"
        username: "{{ vcs_username }}"
        password: "{{ vcs_password }}"
        cluster_name: "{{ cluster_name }}"
        refresh_storage: true
        validate_certs: "{{ validate_certs }}"
      register: hba_info

    - name: Build Datastore
      delegate_to: localhost
      vmware_host_datastore:
        hostname: "{{ ansible_host }}"
        username: "{{ vcs_username }}"
        password: "{{ vcs_password }}"
        validate_certs: "{{ validate_certs }}"
        datastore_type: vmfs
        datastore_name: "{{ datastore_name }}"
        vmfs_device_name: "naa.624a9370{{ hostvars['purefa1']['pure_info']['purefa_info']['volumes'][datastore_name]['serial'] | lower }}"
        vmfs_version: 6
        esxi_hostname: "{{ (hba_info.result | dict2items)[0].key }}"
