---
- name: manage snapshots
  hosts: purefa1
  tasks:
    - name: create snapshot for volume
      delegate_to: localhost
      purestorage.flasharray.purefa_snap:
        name: "{{ vol_name }}"
        suffix: snap
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ api_token }}"
        state: "{{ snap_state | default('present') }}"