---
- name: manage snapshots
  hosts: purefa1
  tasks:
    - name: create snapshot for volume
      delegate_to: localhost
      purestorage.flasharray.purefa_snap:
        name: "{{ vol_name }}"
        suffix: snap2
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ api_token }}"
        state: "{{ snap_state | default('present') }}"

    - name: get snapshot information
      delegate_to: localhost
      purestorage.flasharray.purefa_info:
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ api_token }}"
        gather_subset:
          - snapshots
      register: snap_info

    - name: print snapshot information
      delegate_to: localhost
      debug:
        msg: 
          - "snapshot name: {{ item.key }}"
          - "source volume: {{ item.value.source }}"
      loop: "{{ snap_info['purefa_info']['snapshots'] | dict2items }}"
      when: vol_name in item.key
