---
- name: add hosts and host groups to pure storage arrays
  hosts: purefa1
  tasks:
    - name: create hosts
      delegate_to: localhost
      purestorage.flasharray.purefa_host:
        name: "{{ item.key }}"
        personality: "{{ item.value.personality | default('esxi') }}"
        iqn: "{{ item.value.iqn }}"
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ api_token }}"
      loop: "{{ pure_hosts | dict2items }}"

    - name: Add hosts to hostgroups
      delegate_to: localhost
      purestorage.flasharray.purefa_hg:
        hostgroup: "{{ item.value.host_group }}"
        host: "{{ item.key }}"
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ api_token }}"
      loop: "{{ pure_hosts | dict2items }}"
