---
- name: get lookup info
  hosts: localhost
  # vars:
  #  volume_info: "{{ lookup('csvfile', 'volume_name file=inventory/pure-info.csv') }}"
  #  volume_size: "{{ lookup('csvfile', 'volume_size file=inventory/pure-info.csv') }}"
  #  volume_name: "{{ lookup('csvfile', 'Volume_size file=inventory/pure_volumes.csv', delimiter=',', col=1) }}"
  tasks:
    - name: read csv file
      community.general.read_csv:
        path: inventory/pure_volumes.csv
        fieldnames: volume_name,volume_size
        delimiter: ','
      register: volumes
      delegate_to: localhost

    - name: print vars
      ansible.builtin.debug:
        msg: "{{ volumes['list'] }}"
      # delegate_to: localhost

    - name: loop over vars
      ansible.builtin.debug:
        msg: "{{ item.volume_name }}"
      loop: "{{ volumes['list'] }}"
      when: item.volume_size != 'volume_size'