---
- name: get lookup info
  hosts: localhost
  tasks:
    - name: read csv file
      community.general.read_csv:
        path: csv_input/pure_volumes.csv
        fieldnames: volume_name,volume_size
        delimiter: ','
      register: volumes
      delegate_to: localhost

    - name: print vars
      ansible.builtin.debug:
        msg: "{{ volumes['list'] }}"
      # delegate_to: localhost

    - name: loop over vars
      ansible.builtin.debug:
        msg: "{{ item.volume_name }}"
      loop: "{{ volumes['list'] }}"
      when: item.volume_size != 'volume_size'