---
- name: collect information
  hosts: purefa1
  tasks:
    - name: get list of volumes from csv
      community.general.read_csv:
        path: inventory/pure_volumes.csv
        fieldnames: volume_name,volume_size
        delimiter: ','
      register: volumes
      delegate_to: localhost

    - name: create new volume on purefa1
      delegate_to: localhost
      purestorage.flasharray.purefa_volume:
        name: "{{ item.volume_name }}"
        size: "{{ item.volume_size }}"
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ api_token }}"
        state: "{{ vol_state | default('present') }}"
      loop: "{{ volumes['list'] }}"
      when: item.volume_size != 'volume_size'