---
- name: get lookup info
  hosts: purefa1
  tasks:
    - name: read csv file
      community.general.read_csv:
        path: inventory/assertions_pure_vol.csv
        fieldnames: volume_name,volume_size,datastore,vcenter_cluster
        delimiter: ','
      register: volumes
      delegate_to: localhost

    - name: assert that volume size is between 1G and 20G
      assert:
        that: 
          - "{{ item['volume_size'].split('G')[0] | int  >= 1 }}"
          - "{{ item['volume_size'].split('G')[0] | int  <= 20 }}"
        fail_msg: "{{ item['volume_size'] }} is not between 1G and 20G"
        success_msg: "{{ item['volume_size'] }} is in bounds"
      loop: "{{ volumes['list'] }}"
      when: item.volume_size != 'volume_size'

    - name: assert that volume name is a proper length
      assert:
        that: 
          - "{{ item['volume_name'] | length > 4 }}"
          - "{{ item['volume_name'] | length <= 20 }}"
        fail_msg: "{{ item['volume_name'] }} is an improper name length for a volume name. Must be between 4 and 20 characters"
        success_msg: "{{ item['volume_name'] }} is the proper length for a volume name"
      loop: "{{ volumes['list'] }}"
      when: item.volume_size != 'volume_size'

    - name: assert that no dashes exist in volume name
      assert:
        that: 
          - "{{ '-' not in item['volume_name'] }}"
        fail_msg: "{{ item['volume_name'] }} contains a '-', please use '_' instead"
        success_msg: "{{ item['volume_name'] }} meets character assertions"
      loop: "{{ volumes['list'] }}"
      when: item.volume_size != 'volume_size'