---
- name: create markdown file
  hosts: purefa1

  tasks:
    - name: check configuration information
      delegate_to: localhost
      purestorage.flasharray.purefa_info:
       fa_url: purefa1.lab.local
       api_token: 125cfec6-560a-ca26-e7af-27be411d3959
       gather_subset:
        - volumes
      register: volume_info

    - name: show volume information
      debug:
        msg: 
          - "volume_name: {{ item.key }}"
          - "volume_size: {{ item.value.size | human_readable(unit='G') }}"
      loop: "{{ volume_info['purefa_info']['volumes'] | dict2items }}"

- name: manage datastores in vcenter
  hosts: vmware
  tasks:
    - name: get datastore info
      delegate_to: localhost
      community.vmware.vmware_datastore_info:
        hostname: "{{ ansible_host }}"
        username: "{{ vcs_username }}"
        password: "{{ vcs_password }}"
        datacenter_name: atc
        validate_certs: "{{ validate_certs }}"
      register: datastore_info
      tags: vmw

    - name: show ds information
      debug:
        msg: 
          - "{{ item.name }}"
          - "{{ item.capacity | human_readable(unit='G') }}"
          - "{{ item.provisioned | human_readable(unit='G') }}"
      loop: "{{ datastore_info['datastores'] }}"
      tags: vmw

    - name: create markdown with jinja2 template
      delegate_to: localhost
      ansible.builtin.template:
        src: templates/storage-report.j2
        dest: documentation/pure_storage_report.md

    - name: do a git diff to see if file has changed
      delegate_to: localhost
      shell: git diff documentation/pure_storage_report.md
      register: git_diff
      tags:
        - git
        - diff

    - name: print diff
      delegate_to: localhost
      debug:
        msg: "nothing to commit"
      tags:
        - git
        - diff
      when: git_diff.stdout == ""

    - name: print diff
      delegate_to: localhost
      debug:
        msg: "starting git add commit"
      notify: 
        - add documentation to git staging
      when: git_diff.stdout != ""
      tags:
        - git
        - diff

    - name: run git add commit push
      block:
        - name: add documentation to git staging
          delegate_to: localhost
          shell: git add documentation/pure_storage_report.md
          register: git_add
          tags:
            - git
            - add

        - name: print git message
          debug:
            msg: "{{ git_add }}"
          tags:
            - git
            - add

        - name: commit documentation to git
          delegate_to: localhost
          shell: "git commit -m 'documentation added by ansible'"
          register: git_commit
          tags: 
            - commit
            - git

        - name: print git commit message
          debug:
            msg: "{{ git_commit }}"
          tags:
            - git
            - commit

        - name: push storage documentation to github
          delegate_to: localhost
          shell: git push
          tags:
            - git
            - push
      when: git_diff.stdout != ""
