---
# This action performs a lint of markdown files in the repository

# Name of the action
name: Ansible Linting

# Events which trigger the action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansiblelint:
    name: Lint YAML files
    runs-on: ubuntu-latest

    steps:
      # checkout@v2 action documentation
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # ansible-lint action documentation
      # https://github.com/marketplace/actions/ansible-lint
      - name: Lint Ansible Playbooks
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            ansible-demo/*.yml
          override-deps: |
            rich>=9.5.1,<11.0.0
          args: "-x 301,303,305,602"
